const Actions = {
    GET_TODO_FROM_LS: 'GET_TODO_FROM_LS',
    ADD_NEW_ITEM:'ADD_NEW_ITEM',
    DELETE_ITEM:'DELETE_ITEM',
    SET_CURRENT_ITEM:'SET_CURRENT_ITEM',
    ADD_NEW_COMMENT:'ADD_NEW_COMMENT',
    INCREASE_COMMENTS_COUNTER:'INCREASE_COMMENTS_COUNTER',
    ADD_COMMENT_TO_CURRENT:'ADD_COMMENT_TO_CURRENT'
};

export default Actions;